- name: variable
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
# ansible access variable with two flower brackets
    - name: print task
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.google.com