- name: demo on conditions
  hosts: all
  connection: local
  vars:
    company: true
    model: false
  tasks:
    - name: print car name
      ansible.builtin.debug:
        msg: cars name - suzuki
        when: company is true

    - name: print car name
      ansible.builtin.debug:
        msg: cars name - hundai
        when: model is true